### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by mroberts1** [charming-art/api#233]
Hi, I installed charming with npm and node 20.5.0 but I'm not very familiar with how Javascript works with html and am confused by the examples on the main page.

What do I do now? Do I make an html page and have it import a separate charming.js sketch, such as the import example you give? Or does all the code go in the same html file?

I was also wondering if I can use p5.js to play around with charming, but again am unsure about the initial setup - usually p5 requires an html file, a js file, and a css file.

**Comment by pearmini** [comment]
Glad to hear that you're trying charming.js!

All the code can go in the same html file, say you project is structured as follows:

```txt
- node_modules
- index.html
- package.json
```

```html
<html>
  <div id="app"></div>
  <script src="./node_modules/@charming-art/charming/dist/cm.umd.min.js"></script>
  <script>
    const app = cm.app();

    app.append(cm.circle, {
      x: 100,
      y: 100,
      r: 50,
      fill: "red",
    });

    document.getElementById("app").appendChild(app.render().node());
  </script>
</html>
```

You can also put you code in a separate charming.js sketch, say to create sketch.js in the same directory:

```txt
- node_modules
- sketch.js // add
- index.html
- package.json
```

```js
// sketch.js
const app = cm.app();

app.append(cm.circle, {
  x: 100,
  y: 100,
  r: 50,
  fill: "red",
});

document.getElementById("app").appendChild(app.render().node());
```

```html
<html>
  <div id="app"></div>
  <script src="./node_modules/@charming-art/charming/dist/cm.umd.min.js"></script>
  <script src="./sketch.js"></script>
</html>
```

If you want to use p5.js to play around with charming.js, you should install p5 `npm install p5` and download a sound file:

```txt
- node_modules
- doorbell.mp3 // add
- sketch.js
- index.html
- package.json
```

```html
<html>
  <div id="app"></div>
  <script src="./node_modules/@charming-art/charming/dist/cm.umd.min.js"></script>
  <script src="./node_modules/p5/lib/p5.min.js"></script>
  <script src="./node_modules/p5/lib/addons/p5.sound.min.js"></script>
  <script src="./sketch.js"></script>
</html>
```

```js
// sketch.js
let sound;
function preload() {
  soundFormats("mp3", "ogg");
  sound = loadSound("./doorbell.mp3");
}

function setup() {
  const app = cm.app();

  app.append(cm.circle, {
    x: 100,
    y: 100,
    r: 50,
    fill: "red",
  });

  app.on("mouseClick", () => {
    const mouseX = app.prop("mouseX");
    const mouseY = app.prop("mouseY");
    if (cm.vecDist(cm.vec(mouseX, mouseY), cm.vec(100, 100)) < 50) {
      sound.play();
    }
  });

  document.getElementById("app").appendChild(app.render().node());
}
```

Make sure you start a [local server](https://github.com/processing/p5.js/wiki/Local-server), and you can try it online [here](https://stackblitz.com/edit/stackblitz-starters-xftmm2?file=index.html).

**Comment by pearmini** [comment]
I think there should be a `@charmim-art/charming-sound` for charming's ecosystem in the future. The same example will be like:

```js
const sound = await cm.sound("./doorbell.mp3", { formats: ["mp3", "ogg"] });

const app = cm.app();

app.append(cm.circle, {
  x: 100,
  y: 100,
  r: 50,
  fill: "red",
});

app.on("mouseClick", () => {
  const mouseX = app.prop("mouseX");
  const mouseY = app.prop("mouseY");
  if (cm.vecDist(cm.vec(mouseX, mouseY), cm.vec(100, 100)) < 50) {
    sound.play();
  }
});

document.getElementById("app").appendChild(app.render().node());
```

**Comment by mroberts1** [comment]
Thanks - this helped me figure out a bit better how this fits together. I was able to get the circle, doorbell, etc. from the examples you posted above. :)

Still a few questions though: first, I can't get a sketch to load with the import command at the beginning of a script:

<script>
import * as cm from "@charming-art/charming"; 

[. . .]

</script>

The sketch only seems to load when I remove that line and call the library in the metadata, i.e.:

<html>
  <div id="app"></div>
  <script src="./node_modules/@charming-art/charming/dist/cm.umd.min.js"></script>
  <script>

Also I couldn't get anything to load using the jsdeliver ESM url, even though the url itself is good:

<script type="module">
  import * as cm from "https://cdn.jsdelivr.net/npm/@charming-art/charming/+esm";</script>

So as of now, I can only get it to work by calling the local library in a metadata script.

Hope this makes sense!

**Comment by pearmini** [comment]
>  I can't get a sketch to load with the import command at the beginning of a script:
> <script> import * as cm from "@charming-art/charming"; [. . .] </script>

In this case, you declare a module type:

```html
<script type="module" > import * as cm from "@charming-art/charming"; </script>
```

> Also I couldn't get anything to load using the jsdeliver ESM url, even though the url itself is good:
> <script type="module"> import * as cm from "https://cdn.jsdelivr.net/npm/@charming-art/charming/+esm";</script>

If you declare a module type, you should [start a local server](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts) to host the project, say use Python3:

```python
python3 -m http.server
```

or use [Vite](https://vitejs.dev/):

```bash
npm i vite -D
```

```bash
npx vite dev
```
